# Generated by Django 5.0 on 2023-12-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activated_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='активированный код'),
        ),
    ]
